url: ""
baseurl: wheremagichappen.github.io

# Site settings
title: Where Magic Happen
email: your-email@domain.com
description: "Where Magic Happen is a hyper reality experience that blends virtual and real world."


# Team names, titles and social links
people:
- name: Karan Motreja
  pic: 1
  position: Co-Creator
  social:
    - title: linkedin
      url: #


- name: Minh Nguyen
  pic: 2
  position: Co-Creator
  social:

    - title: linkedin
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Atlas Building Basement
  - line: Boulder Colorado, 80260

# Build settings
markdown: kramdown
permalink: pretty
